### ISSUE TITLE
Reproducing results from Table 2 (Task 1)

### ISSUE THREAD

**Issue by habernal** [thanhan/seqcrowd-acl17#1]
Hello, I like your ACL'17 paper and am interested in re-running your experiments for NER using the HMM-Crowd configuration as reported in Table 2. I looked into the source codes but unfortunately didn't find what should be configured and how to run it. Any hints?

**Comment by thanhan** [comment]
Thanks for your interest.
I have updated the README file, where you will find the instruction to run HMM-Crowd

**Comment by habernal** [comment]
Thank you. I've installed all dependencies (will be in a separate pull request) and successfully ran the experiment but I'm getting the following numbers:

```
(env-python2):~/seqcrowd-acl17$ python hmm.py task1/val/ output.txt
Value error parsing header in AFM: Notice � Copyright SoftMaker Software GmbH and its licensors
Value error parsing header in AFM: Notice � Copyright SoftMaker Software GmbH and its licensors
Value error parsing header in AFM: Notice � Copyright SoftMaker Software GmbH and its licensors
Value error parsing header in AFM: Notice � Copyright SoftMaker Software GmbH and its licensors
Value error parsing header in AFM: Notice � Copyright SoftMaker Software GmbH and its licensors
Value error parsing header in AFM: Notice � Copyright SoftMaker Software GmbH and its licensors
2149 0 11545
num features =  8996
0.681908155186 0.729100529101 0.704715147796
(0.681908155186065, 0.7291005291005291, 0.7047151477958474)
```
Looking into the code, these correspond to P=68, R=73, and F-measure=70. However, Table 2 says P=77, R=72, F=75. Any idea?

**Comment by thanhan** [comment]
I forgot to initialize some parameters in this implementation.
Thanks for catching the bug. I fixed that now.

**Comment by habernal** [comment]
Thanks for fixing that! Still not exactly there yet: 0.780207643031 0.747513227513 0.763510592304 but it's even a bit better :) Closing the issue.

**Comment by thanhan** [comment]
I think you were running on the validation set. In the paper, I reported the results on the test set. If you run on the test set, you will get something like 74.5 F score.

**Comment by habernal** [comment]
Oh, I see, I must have overlooked it. Thanks for clarification!
